Fix issue where an empty required field would throw load Exception
If a field like `sp_entityId` were left empty, which the settings form
allows, then WP SAML Auth would throw an Exception when loading:

```
Fatal error: Uncaught OneLogin\Saml2\Error: Invalid array settings: idp_entityId_not_found, idp_sso_not_found
```